### ISSUE TITLE
Consider supplementing Emacs's .dir-locals.el with package info?

### ISSUE THREAD

**Issue by DivineDominion** [FluxHarmonic/flux-compose#5]
The `.dir-locals.el` is already an Emacs-specific file, so I find no offense in listing Emacs package dependencies used to develop the code base, like `geiser` and what have you. Could be a README section maybe? Just to get viewers up to speed to copy the bare bones of the setup you have @daviwil

**Comment by daviwil** [comment]
Good idea!  That also reminds me that I could potentially add those dependencies to the `manifest.scm` as well so that someone could just run `guix shell` and then launch Emacs directly from there to have all of the dev environment setup needed.

At the very least, a section in the README describing development setup would be useful, I'll add that.

**Comment by daviwil** [comment]
Fixed by 22c84fd, let me know if it needs any more info!

**Comment by DivineDominion** [comment]
That looks plenty helpful, thanks!
